### ISSUE TITLE
Duplicates in latest_result.txt file

### ISSUE THREAD

**Issue by schjonhaug** [mono0926/LicensePlist#137]
When specifying a dependency from GitHub in `license_plist.yml` like so:

```
github:
  - owner: youtube
    name: youtube-ios-player-helper
    version: 1.0.2
manual:
  - name: KeychainItemWrapper
    file: "Challenge/Frameworks/KeychainItemWrapper/LICENSE"
  - name: "Reachability"
    file: "Challenge/Frameworks/Reachability/LICENSE"
  - name: "SwiftGif"
    file: "Challenge/Frameworks/SwiftGif/LICENSE"
  - name: "Firebase"
    file: "Challenge/Frameworks/Firebase/LICENSE"
```

I get duplicates in the `latest_results.txt` file:

```
name: youtube-ios-player-helper, nameSpecified: , owner: youtube, version: 1.0.2

name: youtube-ios-player-helper, nameSpecified: , owner: youtube, version: 1.0.2

name: youtube-ios-player-helper, nameSpecified: , owner: youtube, version: 1.0.2

name: Amplitude-iOS, nameSpecified: Amplitude, owner: amplitude, version: 5.2.0

name: lottie-ios, nameSpecified: Lottie, owner: airbnb, version: 3.1.8

name: swift-sdk, nameSpecified: IterableSDK, owner: Iterable, version: 6.2.8

name: Firebase, nameSpecified: , version: 
body: 
                   …

name: KeychainItemWrapper, nameSpecified: , version: 
body: The MIT License (MIT…

name: Reachability, nameSpecified: , version: 
body: # Reachability

Copy…

name: SwiftGif, nameSpecified: , version: 
body: The MIT License (MIT…

add-version-numbers: true

LicensePlist Version: 2.16.0

```
