### ISSUE TITLE
Remap Name

### ISSUE THREAD

**Issue by Sherlouk** [mono0926/LicensePlist#36]
Certain pod/repo names are not exactly the most readable, would it be possible to add something to the config which would allow remapping of names?

```yaml
rename:
  - randomLib
    name: New Name
```

Or even maybe just for GitHub repos:
```yaml
github:
  - sharethrough/iOS-SDK
    name: "Sharethrough"
  - mono0926/LicensePlist
```

(Where the latter wouldn't be changed as it doesn't have a name node)
