### ISSUE TITLE
Version Numbers

### ISSUE THREAD

**Issue by Sherlouk** [mono0926/LicensePlist#38]
Would it be possible to add a way to automatically add the version number of a library to it's title?

This isn't really feasible for GitHub licenses so maybe they'd need to be a way to manually set this as so: (Not having it just wouldn't add the version)

```yaml
github:
  - account/library
    version: 1.0.1
```

but for CocoaPods/Carthage it should be possible to get the version number from the relevant files?

"LicensePlist (v1.0.1)"

**Comment by Sherlouk** [comment]
@mono0926 
So had a quick look at CocoaPods (I don't work much with Carthage) and its clear the they don't store the version in the acknowledgements.plist file that you currently read from.

With that in mind there would have to be an extra step which parses either the Podfile.lock or Pods/Manifest.lock creating a dictionary for name to version (I've created a regex which can do this: `-(.*)\(([0-9.]*)\)`, it creates two groups the first being the name and the second being the version).

With that dictionary at hand it would be quite easy then iterate through the licenses that you have, check if that license name is within the dictionary and then bind the version number

**Comment by mono0926** [comment]
@Sherlouk 

Thanks, Carthage and CocoaPods both would be okay and thanks for the regex.

For `github` config, I haven't made up my mind.

This is not valid YAML(You can confirm it at [Online YAML Parser](http://yaml-online-parser.appspot.com/)).

```yaml
github:
  - account/library
    version: 1.0.1
```

This is valid format.

```yaml
github:
  - owner: account
    repo: library
    version: 1.0.1
  - account/library # also support current format
```

Or you can specify the version by using the `rename` config.
So, `github` version specification may not be needed to support.

```yaml
rename:
  library: library (1.0.1)
```

---

- [ ] If specified by commit hash on Podfile or Cartfile, how to treat it

**Comment by Sherlouk** [comment]
Agreed with the off by default and maybe `--add-version-numbers` as the flag
If it's a commit hash (which my regex doesn't detect) it should probably show the first 7 characters (as per normal standards)

With regards to GitHub, we could add more purpose to the rename functionality, or simply add a colon to what they already have making it:

```yaml
github:
  - account/library:
    - version: 1.0.0
  - account/otherlib
```
